import React, { useState } from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import {
  calculateSettlements,
} from '../../utils/calculations';
import {
  formatTaka,
  formatMeals,
  formatMonthYear,
} from '../../utils/formatters';
import {
  ArrowRight,
  TrendingUp,
  Copy,
  Check,
  CheckCircle2,
} from 'lucide-react';

export function SettlementView({ summary, currentMonth }) {
  const {
    totalMeals,
    totalContributions,
    mealRate,
    totalOwed,
    totalReceivable,
    memberSummaries,
  } = summary;

  // Calculate optimized transfers
  const transfers = calculateSettlements(memberSummaries);

  // Completed transfers tracking state
  const [completedTransfers, setCompletedTransfers] = useState({});
  const [copied, setCopied] = useState(false);

  function toggleTransfer(transferId) {
    setCompletedTransfers((prev) => ({
      ...prev,
      [transferId]: !prev[transferId],
    }));
  }

  // Generate shareable text for WhatsApp / Messenger group
  function handleCopySummary() {
    let text = `🏠 *HOUSE MEAL SETTLEMENT — ${formatMonthYear(currentMonth).toUpperCase()}*\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `🍲 Total Meals: ${formatMeals(totalMeals)}\n`;
    text += `💰 Total Meal Cost: ${formatTaka(totalContributions)}\n`;
    text += `📈 Final Meal Rate: ${formatTaka(mealRate)} / meal\n\n`;

    text += `📋 *MEMBER BREAKDOWN:*\n`;
    memberSummaries.forEach((m) => {
      const balStr =
        m.status === 'receives'
          ? `+${formatTaka(m.balance)} (Receives)`
          : m.status === 'owes'
          ? `-${formatTaka(Math.abs(m.balance))} (Owes)`
          : `৳0 (Settled)`;
      text += `• ${m.name}: ${formatMeals(m.meals)} meals | Paid ${formatTaka(
        m.contribution
      )} | Cost ${formatTaka(m.mealCost)} | Balance: ${balStr}\n`;
    });

    text += `\n🤝 *SUGGESTED TRANSFERS:*\n`;
    if (transfers.length === 0) {
      text += `All balances are settled! No payments needed.\n`;
    } else {
      transfers.forEach((t, i) => {
        text += `${i + 1}. ${t.fromName}  👉  ${t.toName}:  ${formatTaka(t.amount)}\n`;
      });
    }

    text += `━━━━━━━━━━━━━━━━━━━━━\nGenerated by MealFlow`;

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  const creditors = memberSummaries.filter((m) => m.status === 'receives');
  const debtors = memberSummaries.filter((m) => m.status === 'owes');

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-200 dark:border-slate-800">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-slate-100 tracking-tight">
            Final Settlement &bull; {formatMonthYear(currentMonth)}
          </h1>
          <p className="text-sm sm:text-base text-slate-500 dark:text-slate-400 mt-1">
            Optimized payment transfers to square up all balances with minimum transactions.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="md"
            onClick={handleCopySummary}
            icon={copied ? Check : Copy}
          >
            {copied ? 'Copied to Clipboard!' : 'Copy for WhatsApp / Group'}
          </Button>
        </div>
      </div>

      {/* Key Metric Highlights */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Meal Rate Box */}
        <div className="bg-gradient-to-br from-slate-900 to-slate-800 dark:from-slate-900 dark:to-slate-950 text-white rounded-2xl p-6 shadow-sm border border-transparent dark:border-slate-800 flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs sm:text-sm uppercase tracking-wider text-slate-400 font-bold">
              Final Meal Rate
            </span>
            <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center text-emerald-400">
              <TrendingUp className="w-5 h-5" />
            </div>
          </div>
          <div className="my-4">
            <div className="text-3xl sm:text-4xl font-black tracking-tight text-white">
              {formatTaka(mealRate)}
            </div>
            <p className="text-xs sm:text-sm text-slate-400 mt-1">
              {formatTaka(totalContributions)} total fund &divide; {formatMeals(totalMeals)} meals
            </p>
          </div>
          <div className="text-xs text-slate-400 pt-3 border-t border-slate-700/80 flex justify-between">
            <span>Period: {formatMonthYear(currentMonth)}</span>
            <span className="text-emerald-400 font-bold">Exact Rate</span>
          </div>
        </div>

        {/* Total Receivables Box */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-2xs flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs sm:text-sm uppercase tracking-wider text-slate-500 dark:text-slate-400 font-bold">
              Money to Return (Receivable)
            </span>
            <span className="w-3 h-3 rounded-full bg-emerald-500"></span>
          </div>
          <div className="my-4">
            <div className="text-3xl sm:text-4xl font-black tracking-tight text-emerald-600 dark:text-emerald-400">
              {formatTaka(totalReceivable)}
            </div>
            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
              Due to {creditors.length} members who paid more than consumed
            </p>
          </div>
          <div className="text-xs text-slate-500 dark:text-slate-400 pt-3 border-t border-slate-100 dark:border-slate-800">
            {creditors.map((c) => `${c.name}: +${formatTaka(c.balance)}`).join(' | ') || 'None'}
          </div>
        </div>

        {/* Total Payables Box */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-2xs flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs sm:text-sm uppercase tracking-wider text-slate-500 dark:text-slate-400 font-bold">
              Money to Collect (Payable)
            </span>
            <span className="w-3 h-3 rounded-full bg-rose-500"></span>
          </div>
          <div className="my-4">
            <div className="text-3xl sm:text-4xl font-black tracking-tight text-rose-600 dark:text-rose-400">
              {formatTaka(totalOwed)}
            </div>
            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
              Owed by {debtors.length} members who consumed more than paid
            </p>
          </div>
          <div className="text-xs text-slate-500 dark:text-slate-400 pt-3 border-t border-slate-100 dark:border-slate-800">
            {debtors.map((d) => `${d.name}: -${formatTaka(Math.abs(d.balance))}`).join(' | ') || 'None'}
          </div>
        </div>
      </div>

      {/* Suggested Payment Transfers Section */}
      <Card
        title="Suggested Payment Transfers"
        subtitle="Minimized cash transactions to settle everyone completely"
        action={
          transfers.length > 0 && (
            <span className="text-xs sm:text-sm font-bold text-emerald-700 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/60 px-3 py-1 rounded-full border border-emerald-200/80 dark:border-emerald-800/80">
              {transfers.length} {transfers.length === 1 ? 'transaction' : 'transactions'} required
            </span>
          )
        }
      >
        {transfers.length === 0 ? (
          <div className="text-center py-10">
            <div className="w-14 h-14 rounded-full bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center mx-auto mb-3">
              <CheckCircle2 className="w-8 h-8" />
            </div>
            <h4 className="text-lg font-bold text-slate-900 dark:text-slate-100">Everyone is fully settled!</h4>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              There are no outstanding debts or receivables for {formatMonthYear(currentMonth)}.
            </p>
          </div>
        ) : (
          <div className="space-y-3.5">
            {transfers.map((transfer, idx) => {
              const isDone = Boolean(completedTransfers[transfer.id]);

              return (
                <div
                  key={transfer.id}
                  className={`p-4 sm:p-5 rounded-xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                    isDone
                      ? 'bg-slate-50/70 dark:bg-slate-800/40 border-slate-200 dark:border-slate-800 opacity-50'
                      : 'bg-white dark:bg-slate-800 border-slate-200/90 dark:border-slate-700 shadow-2xs hover:border-slate-300 dark:hover:border-slate-600'
                  }`}
                >
                  {/* From -> To visual pill */}
                  <div className="flex items-center gap-3 sm:gap-5 flex-1">
                    <div className="text-sm font-black text-slate-400 dark:text-slate-500 w-6">
                      #{idx + 1}
                    </div>

                    {/* Debtor (Who Pays) */}
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-full bg-rose-100 dark:bg-rose-950/80 text-rose-700 dark:text-rose-300 font-black text-sm flex items-center justify-center border border-rose-200 dark:border-rose-900/60">
                        {transfer.fromName.charAt(0)}
                      </div>
                      <div>
                        <span className="text-[11px] text-slate-400 dark:text-slate-500 block font-bold uppercase tracking-wider">
                          PAYS
                        </span>
                        <span className="text-sm sm:text-base font-bold text-slate-900 dark:text-slate-100">
                          {transfer.fromName}
                        </span>
                      </div>
                    </div>

                    {/* Middle Arrow with Amount */}
                    <div className="flex flex-col items-center px-2 sm:px-4">
                      <span className="text-xs sm:text-sm font-black text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/80 px-2.5 py-0.5 rounded-full border border-emerald-200/70 dark:border-emerald-800/80 mb-1 whitespace-nowrap">
                        {formatTaka(transfer.amount)}
                      </span>
                      <ArrowRight className="w-5 h-5 text-slate-400 dark:text-slate-500" />
                    </div>

                    {/* Creditor (Who Receives) */}
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-full bg-emerald-100 dark:bg-emerald-950/80 text-emerald-700 dark:text-emerald-300 font-black text-sm flex items-center justify-center border border-emerald-200 dark:border-emerald-900/60">
                        {transfer.toName.charAt(0)}
                      </div>
                      <div>
                        <span className="text-[11px] text-slate-400 dark:text-slate-500 block font-bold uppercase tracking-wider">
                          RECEIVES
                        </span>
                        <span className="text-sm sm:text-base font-bold text-slate-900 dark:text-slate-100">
                          {transfer.toName}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Checkbox / Action */}
                  <div className="flex items-center justify-end pt-2 sm:pt-0 border-t sm:border-t-0 border-slate-100 dark:border-slate-800">
                    <button
                      type="button"
                      onClick={() => toggleTransfer(transfer.id)}
                      className={`inline-flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs sm:text-sm font-bold transition-all cursor-pointer ${
                        isDone
                          ? 'bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-300 dark:hover:bg-slate-600'
                          : 'bg-emerald-600 text-white hover:bg-emerald-700 shadow-2xs'
                      }`}
                    >
                      <Check className="w-4 h-4" />
                      {isDone ? 'Mark as Unpaid' : 'Mark as Transferred'}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </Card>

      {/* Detailed Member Breakdown Table */}
      <Card
        title="Comprehensive Member Settlement Table"
        subtitle="Individual accounting showing consumption vs contribution"
      >
        <div className="overflow-x-auto -mx-6 -mb-6">
          <table className="w-full text-left text-sm sm:text-base">
            <thead className="bg-slate-100/80 dark:bg-slate-800 border-y border-slate-200 dark:border-slate-700 text-xs sm:text-sm uppercase tracking-wider text-slate-600 dark:text-slate-300 font-black">
              <tr>
                <th className="px-6 py-3.5">Member</th>
                <th className="px-5 py-3.5 text-right">Total Meals</th>
                <th className="px-5 py-3.5 text-right">Meal Rate</th>
                <th className="px-5 py-3.5 text-right">Meal Cost</th>
                <th className="px-5 py-3.5 text-right">Total Paid</th>
                <th className="px-5 py-3.5 text-right">Net Balance</th>
                <th className="px-6 py-3.5 text-center">Settlement Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200/80 dark:divide-slate-800">
              {memberSummaries.map((m) => {
                const isPositive = m.balance > 0.01;
                const isNegative = m.balance < -0.01;

                return (
                  <tr key={m.memberId} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/60 transition-colors">
                    <td className="px-6 py-4 font-bold text-slate-900 dark:text-slate-100">{m.name}</td>
                    <td className="px-5 py-4 text-right text-slate-700 dark:text-slate-300 font-semibold">
                      {formatMeals(m.meals)}
                    </td>
                    <td className="px-5 py-4 text-right text-slate-500 dark:text-slate-400 text-xs sm:text-sm">
                      {formatTaka(mealRate)}
                    </td>
                    <td className="px-5 py-4 text-right font-semibold text-slate-700 dark:text-slate-300">
                      {formatTaka(m.mealCost)}
                    </td>
                    <td className="px-5 py-4 text-right font-semibold text-slate-700 dark:text-slate-300">
                      {formatTaka(m.contribution)}
                    </td>
                    <td className="px-5 py-4 text-right font-black">
                      <span
                        className={
                          isPositive
                            ? 'text-emerald-600 dark:text-emerald-400'
                            : isNegative
                            ? 'text-rose-600 dark:text-rose-400'
                            : 'text-slate-500 dark:text-slate-400'
                        }
                      >
                        {isPositive ? `+${formatTaka(m.balance)}` : formatTaka(m.balance)}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <Badge status={m.status}>
                        {m.status === 'receives' && `Receives ${formatTaka(m.balance)}`}
                        {m.status === 'owes' && `Owes ${formatTaka(Math.abs(m.balance))}`}
                        {m.status === 'settled' && 'Settled'}
                      </Badge>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
